@CurrencyConverterApi_HostAddress = http://localhost:5260

POST {{CurrencyConverterApi_HostAddress}}/api/currencies/Create_currency
Accept: application/json

PUT {{CurrencyConverterApi_HostAddress}}/api/currencies/Update_currency
Accept: application/json

GET {{CurrencyConverterApi_HostAddress}}/api/currencies/Get_currency_by_code
Accept: application/json

GET {{CurrencyConverterApi_HostAddress}}/api/currencies/Delete_currency
Accept: application/json

DELETE {{CurrencyConverterApi_HostAddress}}/api/currencies/Get_all_currencies
Accept: application/json

POST {{CurrencyConverterApi_HostAddress}}/api/Conversion
Accept: application/json

GET {{CurrencyConverterApi_HostAddress}}/api/conversion_history
Accept: application/json

GET {{CurrencyConverterApi_HostAddress}}/api/analytics/most_popular
Accept: application/json

GET {{CurrencyConverterApi_HostAddress}}/api/analytics/weekly_stats
Accept: application/json

GET {{CurrencyConverterApi_HostAddress}}/api/analytics/rates_month
Accept: application/json

###