@CurrencyConverterApi_HostAddress = http://localhost:5260

POST {{CurrencyConverterApi_HostAddress}}/api/currencies/create
Content-Type: application/json

PUT {{CurrencyConverterApi_HostAddress}}/api/currencies/update
Accept: application/json

GET {{CurrencyConverterApi_HostAddress}}/api/currencies/get-currency-by-code
Accept: application/json

GET {{CurrencyConverterApi_HostAddress}}/api/currencies/all-currencies
Accept: application/json

DELETE {{CurrencyConverterApi_HostAddress}}/api/currencies/delete
Accept: application/json

POST {{CurrencyConverterApi_HostAddress}}/api/conversions
Content-Type: application/json

GET {{CurrencyConverterApi_HostAddress}}/api/conversion-history
Accept: application/json

GET {{CurrencyConverterApi_HostAddress}}/api/analytics/most-popular
Accept: application/json

GET {{CurrencyConverterApi_HostAddress}}/api/analytics/weekly-stats
Accept: application/json

GET {{CurrencyConverterApi_HostAddress}}/api/analytics/rates-month
Accept: application/json